version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - '80:80'
      - '443:443'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
      MYSQL_USER: ${MYSQL_USER:?err}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
    volumes:
      - './app:/var/www/html'
      - './docker/nginx/config:/etc/nginx/conf.d'
      - './docker/nginx/entrypoint:/entrypoint'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: ${APP_NAME:?err}-mysql
    restart: 'on-failure'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
      MYSQL_USER: ${MYSQL_USER:?err}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    volumes:
      - ${PWD}