controllers:
    resource: ../src/Controller/
    type: attribute

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        # this value can be an absolute path or an absolute URL
        path: /admin
        permanent: false