sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            user:
                label: Users
                items:
                    - admin.user
            event:
                label: Events
                items:
                    - admin.event
                    - admin.ticket
            utilities:
                label: Utilities
                items:
                    - route: app_utility_upload_users_csv
                      label: Upload User CSV
                    - route: app_utility_upload_tickets_csv
                      label: Upload Ticket CSV


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
