sonata_admin:
    title: 'Marti Parti Admin'
    title_logo: 'assets/images/logo.jpg'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            user:
                label: Users
                translation_domain: messages
                items:
                    - admin.users
            event:
                label: Events
                translation_domain: messages
                items:
                    - admin.events
                    - admin.tickets
            utilities:
                label: Utilities
                translation_domain: messages
                items:
                    - route: app_utilities_upload_users_csv
                      label: Upload User CSV
                    - route: app_utilities_upload_tickets_csv
                      label: Upload Ticket CSV


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
