name: Terraform Plan
on:
  pull_request:

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    permissions:
      actions: read
      contents: read
      security-events: read
    steps:
#     - name: Clone repo
     - uses: actions/checkout@v3
#     - uses: Yellow-Box-Software/terraform-action@v2.5
     - uses: hashicorp/setup-terraform@v2
       with:
         terraform_wrapper: false

     - name: Formatting Check
       id: fmt
       run: terraform fmt -check
       continue-on-error: true

     - name: Security scan
       id: tfsec
       uses: aquasecurity/tfsec-action@master
       with:
         soft_fail: true

     - name: Authenticate with Google Cloud
       id: auth
       uses: actions-hub/gcloud@master
       env:
         PROJECT_ID: ${{ secrets.GCP_PROJECT }}
         APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
       with:
         args: iam service-accounts keys create terraform/gcloud-service-key.json --iam-account github-deploy@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com && chown 1001:121 terraform/gcloud-service-key.json

     - name: Initialize Terraform
       id: init
       env:
         GOOGLE_APPLICATION_CREDENTIALS: gcloud-service-key.json
       run: pwd && ls -al; terraform init -backend-config='bucket=${{ secrets.TF_BUCKET }}'

     - name: Terraform Validate
       id: validate
       run: terraform validate

     - name: Terraform Plan
       id: plan
       env:
         GOOGLE_APPLICATION_CREDENTIALS: gcloud-service-key.json
       run: >
           terraform plan
           -var "gcp_project=${{ secrets.GCP_PROJECT }}"

